@startuml
'https://plantuml.com/class-diagram

class Main
class FileIO
class TodoList
class Item

Main "1" *-- FileIO
Main "1" *-- TodoList
TodoList "0..many" o-- Item

class Item {
    - String description
    - boolean done
    + Item(String desc)
    + Item(String desc, boolean done)
    + String getDescription()
    + boolean isDone()
}
class TodoList {
    - List<Item> items
    + TodoList()
    + void addItem(Item item)
    + List<Item> getItems()
}

class FileIO {
    - String path
    - String header
    + FileIO(String path, String header)
    + void saveData(List<Item> items)
    + List<Item> readData()
}

@enduml